### ISSUE TITLE
Comparators (Vanilla and PR) do not update when a Magneticraft inserter adds items to an inventory

### ISSUE THREAD

**Issue by Redquaker** [PFAA-Updates/PFAA-Issues#16]
See: https://discord.com/channels/352813033145368579/373983954103042048/880143157772320828

Could possibly make inserters perform a block update?

![image](https://github.com/user-attachments/assets/f6df5f88-fc4e-4532-9a37-1bd80fee632c)
![image](https://github.com/user-attachments/assets/47973c01-dd9a-4565-8897-fc9ccdafd157)

**Comment by Sukasa** [comment]
Needs to trigger a block update on the receiving entity.  Should be reasonably doable.

**Comment by Sukasa** [comment]
Fixed with a modification to IE, so that the crate calls markDirty() when it's updated
