### ISSUE TITLE
Some items in NEI with % chance outputs no longer show as such

### ISSUE THREAD

**Issue by Redquaker** [PFAA-Updates/PFAA-Issues#18]
For example, milled mica from the IE crusher. I believe this should be a 50% chance to output.

![image](https://github.com/user-attachments/assets/833d4549-e0fa-4ddc-a360-008bbd333075)

**Comment by Sukasa** [comment]
![image](https://github.com/user-attachments/assets/33469cb5-de8b-458b-912b-a87232c7aa4b)
Appears to be fixed with an NEI update to latest GTNH.  Closing as completed.
