### ISSUE TITLE
HQM Ice reward not compatible with TFC Cellar

### ISSUE THREAD

**Issue by Sukasa** [PFAA-Updates/PFAA-Issues#21]
The ice being given by the quest when making cellar blocks is reportedly not compatible with the cellar controller.  We either need to make it give the proper ice block, or minecraft:snow_block

**Comment by Terra1125** [comment]
The Celler can already use Minecraft snow blocks with no issue but snowballs do not work I tested this with the Celler Im made under Red's house

**Comment by xenten9** [comment]
This is because it gives you TFC ice which needs to be used with the ice saw to break and give vanilla ice. I believe this was originally done to make the reward not just give you a bunch of free coolant especially if you were somewhere warm, and would require you to invest in an ice saw.

**Comment by xenten9** [comment]
This has already been resolved in my changes to the HQM quest book as the quest gives you snow blocks instead.
