### ISSUE TITLE
Techguns Ore Cluster Scanner readouts do not print proper names for custom ore clusters

### ISSUE THREAD

**Issue by Redquaker** [PFAA-Updates/PFAA-Issues#28]
![image](https://github.com/user-attachments/assets/06e40a16-0d78-490b-b2d1-a450f9478dec)

**Comment by Sukasa** [comment]
Looks like custom ore clusters don't have lang file entries.  The easiest way to do this is probably going to just be to add lang entries to PFAATweaks.

**Comment by Sukasa** [comment]
Added lang file entries to PFAATweaks mod
