### ISSUE TITLE
Sandwiches quest in HQM book does not detect sandwiches

### ISSUE THREAD

**Issue by zingewill** [PFAA-Updates/PFAA-Issues#9]
Did not thoroughly test the quest to see if I could fins a sandwich that completes it. May be related to how Cooking With TFC handles sandwiches, as it gives them different names based on the ingredients used (ham, steak, roast beef, veggie, etc.)

**Comment by Terra1125** [comment]
This is a side effect of Cooking with TFC changing how Sandwiches are made from normal TFC, when you get the Blender & make a "Perfect" Sandwich the quest is marked as completed

**Comment by xenten9** [comment]
This issue is resolved in my tweaks to the HQM quest book as the sandwich quest is no longer an actual quest but rather more a note that its possible once the requisite quests have been completed.
